### ISSUE TITLE
RainbowParentheses interferes with highlighting [was: No highlighting for references]

### ISSUE THREAD

**Issue by RomainEndelin** [vim-pandoc/vim-pandoc-syntax#107]
Hi,

When I edit `tests/refs.pdc, I can't get any highlighting on the references and link, whether they are inline or not. It is only displayed as a normal text.

However, footnotes with the format `^[another footnote.] ` are correctly highlighted (not if the `^` is inside the brackets), as well as `*[PCL]: P C L`.
Images are prepended by `▨`, but not highlighted.

**Comment by RomainEndelin** [comment]
Sorry for the late reply.

I get `['level16']` as an answer of `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`, either when having the cursor on the label or on the link.

I also tried with gvim, and I don't have highlighting either.

**Comment by fmoralesc** [comment]
Ajá! It seems like you have RainbowParenthesis installed? Somehow it created a conclict with vim-pandoc-syntax's highlighting.

**Comment by RomainEndelin** [comment]
Oh yes, you're right! I disabled `RainbowParenthesis` and it now works.

Thanks for the help.
