### ISSUE TITLE
Can the syntax highlighting be active between <div>...</div> html block?

### ISSUE THREAD

**Issue by dnguyen85** [vim-pandoc/vim-pandoc-syntax#108]
Hi, 

I use pandoc markdown to mix html `<div>`...`</div>` block and markdown extensively. When using vim-pandoc-syntax, I find that the syntax highlighting disappears inside the `<div>` block. Is there a way to force markdown syntax highlighting to work inside html `<div>` blocks?

Thanks for your help in advance.

**Comment by fmoralesc** [comment]
Can you give me some sample text where this happens?

**Comment by dang2327** [comment]
Here is an example: (note that all headers but the first one following a `<div>` tag are properly highlighted)

![2015_01_05_img01](https://cloud.githubusercontent.com/assets/230603/5616841/41403a52-94d6-11e4-9958-d7805c066c5f.png)

**Comment by fmoralesc** [comment]
Ah! The header not being highlighted is because vim-pandoc-syntax requires headers to have an empty line before them. I guess it should take this case in consideration, I imagine pandoc parses that just fine?

**Comment by dang2327** [comment]
Yes, pandoc parses the document without any problem. Plus, all is well if I add an empty line before the first header:

![2015_01_05_img02](https://cloud.githubusercontent.com/assets/230603/5617450/f2d329ea-94dc-11e4-9da6-d6e5f300dcb8.png)

This is a quick and easy way to resolve this. I don't think a fix is necessary.
