### ISSUE TITLE
List syntax doesn't pass tests

### ISSUE THREAD

**Issue by rafaeln** [vim-pandoc/vim-pandoc-syntax#109]
On Ubuntu 14.04.1, using vim 7.4.052 installed from official repositories, the lists in `vim-pandoc-syntax/tests/block.pdc` aren't highlighted correctly.

![screenshot from 2015-01-07 17 31 51](https://cloud.githubusercontent.com/assets/2940362/5656031/027dd0c6-9694-11e4-9af3-454a8a05455b.png)

I installed vim-pandoc-syntax using Pathogen. The vimrc I was using when I got that screenshot is

~~~vim
filetype plugin on

let g:pathogen_disabled = ['flappyvird-vim', 'goyo.vim', 'gundo', 'LaTeX-Box', 'python-mode', 'repmo.vim', 'seoul256.vim', 'smartpairs.vim', 'ultisnips', 'vim-abolish', 'vim-characterize', 'vim-colors-solarized', 'vim-commentary', 'vim-easy-align', 'vim-eunuch', 'vim-fugitive', 'vim-gitgutter', 'vim-markdown', 'vim-obsession', 'vim-repeat', 'vim-scriptease', 'vim-sensible', 'vim-snippets', 'vim-surround', 'vim-tmux-navigator', 'vim-unimpaired', 'vim-vinegar', 'vim-visual-star-search', 'vim-yankstack']

execute pathogen#infect()
~~~

**Comment by fmoralesc** [comment]
Yes, there was a regression recently. Will check asap.

**Comment by rafaeln** [comment]
You are right. This is a regression. Commit `6ef7676e704ec62a50223f8fe787f4c9edc88548` passes the test.

**Comment by fmoralesc** [comment]
Reverted commit 1d54c4c164e3966a10a81f7665530f56a0ff6dfb, which was faulty. Thanks for the heads up.
