### ISSUE TITLE
Indented blockquote isn't highlighted

### ISSUE THREAD

**Issue by rafaeln** [vim-pandoc/vim-pandoc-syntax#111]
Blockquotes aren't highlighted if they're indented.

![screenshot from 2015-01-08 11 06 12](https://cloud.githubusercontent.com/assets/2940362/5667626/8289feb0-9726-11e4-8d5a-a48ee80332b1.png)

**Comment by fmoralesc** [comment]
Thanks for the heads up. Just fixed in master.
