### ISSUE TITLE
Character replacement for html code start and end is not available in Consolas and Cousine fonts

### ISSUE THREAD

**Issue by mhminai** [vim-pandoc/vim-pandoc-syntax#112]
I would like to suggest that the default glyphs used to replace html comment start and end be some that are supported in the common font families.
This is definitely very subjective, but I found that the glyph for html comment start and end was not supported even in Consolas and Cousine, which I would assume would be popular for pandoc users.

**Comment by mhminai** [comment]
This is probably a addendum to #4

**Comment by fmoralesc** [comment]
Good idea. I just changed the defaults to `‹` and  `›`. The old defaults were gnarly anyway, you gave me perfect excuse to change them.

BTW, in case you need to override one of the defaults, you should do this
~~~ vim
    let g:pandoc#syntax#conceal#cchar_overrides['html_c_s'] = '‹'
~~~
