### ISSUE TITLE
Links not highlighted in list items 

### ISSUE THREAD

**Issue by rafaeln** [vim-pandoc/vim-pandoc-syntax#115]
Links in non-initial lines of list items aren't properly highlighted. Anything that follows them in other lines is also not properly highlighted. The output of `echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` on the `[` on line 4 is `['pandocCodeblock']`, as showed below.

![image](https://cloud.githubusercontent.com/assets/2940362/5727152/2594fa92-9b1e-11e4-9296-d1d6fbe93096.png)

**Comment by fmoralesc** [comment]
Same issue as #114, only different character. I tried using a more lax rule for list item continuations, but that caused regressions. It's best to go one char at a time.

Just pushed a fix.

**Comment by rafaeln** [comment]
This fix fixed it.
