### ISSUE TITLE
Underscores in autolinks are not ignored

### ISSUE THREAD

**Issue by gauthma** [vim-pandoc/vim-pandoc-syntax#117]
If links with an underscore (like say, this one: https://www.youtube.com/watch?v=_oAKtBpdZSw) are put in autolinks with `<linkwithone_underscore>`, the underscores are NOT ignored for emphasis purposes, as I think they ought to be. Escaping the `_` causes the `\` to be shown in the final html...

If the link is typeset like so: `[link text](linkwithone_underscore)`, the underscore is ignored.

**Comment by fmoralesc** [comment]
Are you using
    
      https://www.youtube.com/watch?v=\_oAKtBpdZSw

or 

     <https://www.youtube.com/watch?v=_oAKtBpdZSw>

? pandoc renders the first as text, and the second as a link, and with the second I don't get the emphasis issue (I'll push a tweak to make sure). Are you using something else than pandoc to render the markdown text?

**Comment by gauthma** [comment]
I came across this issue when using gitit (which AFAIK uses pandoc). With 

`[link text](https://www.youtube.com/watch?v=_oAKtBpdZSw)`

everything works fine (i.e. the underscore is ignored for emphasis and the link produced in the output is correct). With 

`<https://www.youtube.com/watch?v=_oAKtBpdZSw>`

the text after the underscore is emphasised (but the output is correct). Adding an escape backslash

`<https://www.youtube.com/watch?v=_oAKtBpdZSw>`

causes the extraneous emphasising to disappear, but the backslash is part of the link produced in the output...

**Comment by fmoralesc** [comment]
Can you try with the tweaks I just pushed to master?

**Comment by gauthma** [comment]
Sorry still doesn't work :(

**Comment by gauthma** [comment]
I just noticed something: this issue only happens when the `<link>` is *inside a bullet list*!! I'm sorry I didn't mention this earlier it did not seemed relevant :(

**Comment by fmoralesc** [comment]
Ahá! I just pushed a fix for this, it was an oversight.

**Comment by gauthma** [comment]
Yep, it works now!
