### ISSUE TITLE
unconcealing.

### ISSUE THREAD

**Issue by naught101** [vim-pandoc/vim-pandoc-syntax#132]
Is there a way to disable the behaviour implemented at #80 , as well as any other character conversion (e.g. hiding `$` signs in latex, and conversion of `*` and `-` to bullets)? I find the expansion in contraction, and the flickering when moving lines to be really distracting, and would prefer to just see actual markdown, with pandoc highlighting.

I seem to be able to turn this behaviour off with `:set conceallevel=0`, but I can't see any vim-pandoc-syntax options that work: `:help pandoc-syntax-configuration` doesn't exist (VPS installed via pathogen, latest github version, vim 7.4 (kubuntu default)), and I have `let g:pandoc_use_conceal = 0` in my .vimrc, but it does nothing.

**Comment by fmoralesc** [comment]
pathogen probably didn't update the help tags file. You can see all the settings available at the help file [here](https://github.com/vim-pandoc/vim-pandoc-syntax/blob/master/doc/pandoc-syntax.txt#L14-L77).

You'll probably want
~~~ vim
let g:pandoc#syntax#conceal#use = 0
~~~

**Comment by naught101** [comment]
True, `:call pathogen#helptags()` makes the help appear, and that does work. Thanks!
