### ISSUE TITLE
LaTeX replacement: handle mutli-letter subscripts

### ISSUE THREAD

**Issue by 5nizza** [vim-pandoc/vim-pandoc-syntax#134]
![pandoc-bug-latex2](https://cloud.githubusercontent.com/assets/928552/7069335/6ca4b604-ded8-11e4-942b-4e985e6d52fe.png)

becomes

![pandoc-bug-latex](https://cloud.githubusercontent.com/assets/928552/7069336/7146198c-ded8-11e4-8c26-73eb30dd5d89.png)

Either `fin` should be all subscripted (which unlikely i think), or nothing should be subscripted.

Kind regards.

**Comment by fmoralesc** [comment]
this is an issue in com's TeX support, vim-pandoc doesn't handle that.
