### ISSUE TITLE
Highlight groups not shown

### ISSUE THREAD

**Issue by vyp** [vim-pandoc/vim-pandoc-syntax#140]
Previously, after pressing `:hi<cr>` in normal mode, which shows the highlight groups, I would be able to see all the highlight groups relevant to this plugin (prefixed with 'pandoc'). But I do not see them anymore.

Is there another way to get the list of pandoc highlight groups available to tweak? To clarify, I mean the groups like `pandocEmphasis`, `pandocStrong` etc.

**Comment by fmoralesc** [comment]
This is weird, it should work as always. I hope to go back to this plugin this weekend, will see what I can do.

**Comment by vyp** [comment]
Oh, it could also just be something wrong with my setup. I forgot to ask if you can see them or not.

**Comment by fmoralesc** [comment]
I'll have to check when I'm home later today; I don't have my vim setup here at work with me.

**Comment by vyp** [comment]
No worries.

**Comment by fmoralesc** [comment]
Anyway, you can always check the syntax file itself to see what is available. To check which rule applies for the character under the cursor, I use these commands:

~~~ vim
command! SynName echo synIDattr(synID(line("."), col("."), 1), "name")
command! SynStack echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
command! SynTrans echo synIDattr(synIDtrans(synID(line('.'), col('.'), 1)), "name")
~~~

(https://github.com/fmoralesc/dotfiles/blob/master/.vimrc#L332-L334)

**Comment by vyp** [comment]
Argh, this actually stemmed from my inexperience with vim (even though I've been using it for a long time :\\). I didn't realise the `:hi` command only shows whats currently loaded (or something like that). I thought it just showed all groups available. (So I was running it from a non markdown file expecting to see the pandoc groups...)

Sorry for the inconvenience. >_<

**Comment by fmoralesc** [comment]
No problem ;)
