### ISSUE TITLE
Bold + Italic not working

### ISSUE THREAD

**Issue by nathanesau** [vim-pandoc/vim-pandoc-syntax#146]
![vim-pandoc-bug](https://cloud.githubusercontent.com/assets/4649987/7785189/3c3d8fe4-0139-11e5-8fe7-2bc4c928d19e.png)

Bold and italic text is not rendering properly for me in Vim, Version 7.4.52 (picture attached). There's also an issue with Latex subscripts and superscripts that I point out.

**Comment by fmoralesc** [comment]
The LaTeX subscripts problems is out of scope for us (it's reponsibility of vim's LaTex highlighting). I'll see what I can do about the other issue, although it looks like a terminal configuration issue (gnome-terminal might need this: http://www.reddit.com/r/vim/comments/24g8r8/italics_in_terminal_vim_and_tmux/)

**Comment by nathanesau** [comment]
OK the problem with the italic and bold had to go with my terminal not your plugin. do you know which files are responsible for the LaTeX highlighting or which plugin on github deals with this issue?

**Comment by fmoralesc** [comment]
Sadly, the LaTeX syntax file is developed outside of github, but you can reach the author at drchip@campbellfamily.biz. It is a known issue, though, and I'm sure he has received many reports about it already :p (see #52, #134).
