### ISSUE TITLE
Background colour of math symbols is grey rather than black

### ISSUE THREAD

**Issue by sjackman** [vim-pandoc/vim-pandoc-syntax#147]
The background colour of my MacVim configuration is black. The background colour of math symbols, such as `$\approx$`, is grey rather than the expected black.

**Comment by fmoralesc** [comment]
That is most likely because of the theme not supporting the concealed syntax elements. Try executing
~~~
hi! link Conceal Special
~~~
You might want to add that to your vimrc after setting your colorscheme.

**Comment by sjackman** [comment]
I'm using [railscat.vim](https://gist.github.com/jeffkreeftmeijer/1523432). Your fix worked! Thanks. See https://github.com/sjackman/dotfiles/commit/fb1cde14148c1cffde80550ce367cdbbee8251a6
