### ISSUE TITLE
Pipe character for line breaks

### ISSUE THREAD

**Issue by sjackman** [vim-pandoc/vim-pandoc-syntax#148]
Pipe symbols at the beginning of a line can be used for line breaks in Markdown. Oddly, I can't find a citation for this now, but it definitely works. vim-pandoc-syntax interprets this as a table, and further syntax highlighting after the pipe symbol seems to be disabled.

```
| line 1
| line 2
| line 3
```

**Comment by fmoralesc** [comment]
Just pushed a fix to master.

**Comment by sjackman** [comment]
Thanks!
