### ISSUE TITLE
do not hide backslashes in newcommands

### ISSUE THREAD

**Issue by anntzer** [vim-pandoc/vim-pandoc-syntax#167]
pandoc is able to handle \newcommands (http://pandoc.org/README.html#latex-macros).  As such it would be nice if backslashes were not hidden in lines where a \newcommand is defined.

**Comment by fmoralesc** [comment]
Can you send me a sample where this happens? Within LaTeX elements we defer to vim's latex syntax, so perhaps it's an external issue. Otherwise I'll look into it.

**Comment by anntzer** [comment]
![screenshot_20160224_145712](https://cloud.githubusercontent.com/assets/1322974/13303951/fae6a4b0-db06-11e5-91c1-db5ebc206a2a.png)
Same file, the cursor is on the left window.

**Comment by fmoralesc** [comment]
I can't reproduce, this is what I see:

![captura de pantalla de 2016-02-26 11-32-31](https://cloud.githubusercontent.com/assets/221465/13349851/a6f91f00-dc7c-11e5-9a93-74c4fb090ad2.png)

Are you sure you don't have a different plugin that might be doing this? I imagine LaTeX-Box or vim-latex might be affecting LaTeX highlighting.

As a test, put your cursor over one of the concealed `\`s, and execute this command: 
~~~ vim
echo synIDattr(synID(line("."), col("."), 1), "name")
~~~

**Comment by anntzer** [comment]
The syntax group is `pandocBackslash`.
I have Latex-Box and `let g:tex_conceal = "abdmg"` in my vimrc but commenting them out doesn't help.

**Comment by fmoralesc** [comment]
Use
~~~
let g:pandoc#syntax#conceal#backslash == 0
~~~
That is the default, you must have enabled it somewhere.

**Comment by anntzer** [comment]
Indeed, my bad.

**Comment by fmoralesc** [comment]
Yes, the thought just occured to me also. I'll see what I can do....
