### ISSUE TITLE
Most recent pull request (#169) breaks vim-pandoc-syntax

### ISSUE THREAD

**Issue by mowgli** [vim-pandoc/vim-pandoc-syntax#171]
After updating to the most recent commit that merged #169, vim-pandoc-syntax is not working anymore and throws many error messages.

**Comment by mowgli** [comment]
Fehler beim Ausführen von "/xxx/.vim/bundle/vim-pandoc-syntax/syntax/pandoc.vim":
Zeile   68:
E721: Doppelter Schlüssel im Wörterbuch: "codelang"
E15: ungültiger Ausdruck: { "newline": " ", "image": "i", "super": "^", "sub": "_", "strike": "~", "atx": "#",  
"codelang": "l","codelang": "-","abbrev": "a","footnote": "f","definition": " ","li": "*","html_c_s": "+","html_
c_e": "+"}
Zeile  207:
E121: Undefinierte Variable: s:cchars
E116: Ungültige Argumente für die Funktion <SNR>111_WithConceal
…

**Comment by fmoralesc** [comment]
I think I know what the problem is. Just to confirm, what is the value of &encoding in your config? (`echom &encoding`).

**Comment by mowgli** [comment]
latin1

**Comment by fmoralesc** [comment]
As I suspected. Please check if the latest commit fixes it.

**Comment by mowgli** [comment]
Yes, fixes it.
