### ISSUE TITLE
Enable folding of the yaml metablock

### ISSUE THREAD

**Issue by joelostblom** [vim-pandoc/vim-pandoc-syntax#176]
Would it be possible to add folding for the yaml metablock? The rationale would be that the metadata is not modified as often as the content of the file and viewing it every time a file is opened is not necessary. This would also help when writing long abstracts that can be contained in the "abstract" field of the metadata block, but sometimes take up half the screen and cannot be folded away.

The folding could work similar to how headings have all their content folded by default when opening up a file. If the file starts with `---`, then fold to the next `---` or `...`.

**Comment by fmoralesc** [comment]
Sure, I'll see what I can do.

**Comment by fmoralesc** [comment]
Wait, isn't 
``` vim
let g:pandoc#folding#fold_yaml = 1
```
enough? This is handled in vim-pandoc, not vim-pandoc-syntax.

**Comment by joelostblom** [comment]
Ah yes, my apologies, I forgot that there are two parts to this plugin. I only searched in `vim-pandoc-syntax` for that functionality. The `let g:pandoc#folding#fold_yaml = 1` option works exactly as I want.

Before opening another misinformed issue, maybe I can ask you another question here first. Is there a way of displaying the folded version of all the headings and subheadings, but none of the paragraph texts? Basically, the same as from `:TOC`, but shown by default when the document is opened. And then, the paragraph text could be expanded by going to a header and unfolding it, but each headers subheadings would always be visible, does that make sense?

It would look something like this:
![screenshot from 2016-03-18 01-38-39](https://cloud.githubusercontent.com/assets/4560057/13869366/382210c6-ecaa-11e5-94be-595286abe179.png)

I tried playing around with `g:pandoc#folding#level`, but couldn't get it to work. Maybe I'm missing something again.

**Comment by fmoralesc** [comment]
You want
``` vim
let g:pandoc#folding#mode = 'stacked'
```
for that ;)

See `:help vim-pandoc-folding-module', there's a bunch of options for this.

**Comment by joelostblom** [comment]
Great! I must improve my documentation reading skills. I noticed the `syntax` and `relative` folding options, but for some reason, I skipped right over `stacked`. I will stop suggesting existing features now =) Thank you!

**Comment by slowkow** [comment]
How do you turn folding off?

None of these settings disables folding:

```vim
let g:pandoc#folding#mode = 'off'
let g:pandoc#folding#mode = 0
let g:pandoc#folding#level = 0
let g:pandoc#folding#fdc = 0
```

This works, but it seems like the code required for folding is still running and slowing down vim. I would prefer to disable the folding code entirely, so it does not slow down vim. Is that possible?

```vim
let g:pandoc#folding#level = 100
```

**Comment by fmoralesc** [comment]
@slowkow, To disable folding entirely, add the folding module to the blacklist: 

```
let g:pandoc#modules#blacklist = ['folding']
```
Although your comment made me think that we should have something like `pandoc#folding#enable` (for each module), as an alternative.

**Comment by slowkow** [comment]
@fmoralesc 

Your suggestion does not work for me. Folding is not disabled when I put this in my `~/.vimrc`:

```vim
let g:pandoc#modules#blacklist = ['folding']
```

**Comment by fmoralesc** [comment]
Sorry, it was `disabled` instead of `blacklist`.
