### ISSUE TITLE
Almost all words are highlighted

### ISSUE THREAD

**Issue by schmittlauch** [vim-pandoc/vim-pandoc-syntax#204]
Often some single words are highlighted and I don't know why. This happens mostly with "normal" words without special markdown syntax (also in lists), but sometimes headings are affected, too.
Here's a screenshot of this problem: 
![screenshot_20161119_210409](https://cloud.githubusercontent.com/assets/1479555/20458138/324f9d6c-ae9c-11e6-8843-5350e8e4fc4c.png)

I used the following markdown text:

```
# Foobar 23 42 asdf

foo bar asdf hjkl
lmnoöpzßda

## heading 2

- foo
- bar
    - foobar

### heading 3
```

I'm using vim 7.4 with vim-pandoc and vim-pandoc-syntax
This may be related to #195 as the problem looks similar. I'm not using a custom colorscheme, though.

**Comment by fmoralesc** [comment]
That looks like the spellchecker is closing those words. Try `set nospell`.

**Comment by schmittlauch** [comment]
You're right, that fixed it \0/

But how did vim-pandoc activate this? Shall I just add nospell to the options for FileType markdown or is there something in vim-pandoc that should be fixed?

**Comment by fmoralesc** [comment]
Vim-pandoc enables the spellchecker by default, you can put the "spell"
checker in the list of disabled modules; check the help file for
instructions.

**Comment by schmittlauch** [comment]
Thank you, that solved it.

**Comment by weibeld** [comment]
Just for reference, to put the "spell" module in the list of disabled modules, you can put the following in your `.vimrc` file:

    let g:pandoc#modules#disabled = [ "spell" ]

The relevant section of the `vim-pandoc` help file can be displayed with `:help vim-pandoc-settings`.
