### ISSUE TITLE
Formatting of emphasised text is gone with Goyo

### ISSUE THREAD

**Issue by maxigaz** [vim-pandoc/vim-pandoc-syntax#211]
When I'm in a file that has emphasised text in it (e.g. `*some emphasis*`) and turn on and off [Goyo](https://github.com/junegunn/goyo.vim) with `:Goyo`, the formatting of the emphasised text is gone, so it is no longer in italics.

When this happens, the only way to restore the correct formatting is restarting Neovim completely. (I'm using Neovim 0.1.7, by the way.)

Edit: I can also reproduce the issue by simply sourcing init.vim.

**Comment by jloow** [comment]
This also happens for me when changing from light background to dark (eg `set background=dark`) or the other way around. I'm also using nvim.

**Comment by alerque** [comment]
Confirmed, thanks for the tip @jloow. I'm able to reproduce this with that switch as well.
