### ISSUE TITLE
E127: Cannot redefine function EnableEmbedsforCodeblocksWithLang: It is in use

### ISSUE THREAD

**Issue by bpj** [vim-pandoc/vim-pandoc-syntax#213]
Whenever I try to use `:PandocHighlight` *more than once*, or if I try to reset
the `g:pandoc#syntax#codeblocks#embeds#langs` variable I get this error message:

```
Error detected while processing /home/benct/.vim/bundle/vim-pandoc-syntax/syntax/pandoc.vim:
line  160:
E127: Cannot redefine function EnableEmbedsforCodeblocksWithLang: It is in use
```

If I have this at the top of my .vimrc (preceded only by `nocompatible` and `fileencoding`, notably before any plugins are loaded

```
let g:pandoc#syntax#codeblocks#embeds#langs = [
            \'perl',
            \'yaml',
            \'html',
            \'latex=tex',
            \'markdown=pandoc',
            \]
```

no syntax highlighting happens and what's more the above error message appears whenever I load a new pandoc file, or set the filetype or syntax to pandoc the error appears. I've tried to disable all after/syntax files and the like but to no avail. Maybe I am misunderstanding something, but the embedded syntax feature is unusable for me.

**Comment by fmoralesc** [comment]
I think the issue is that you are trying to embed markdown code, and that causes some kind of recursion error (it seems to try to define `EnableEmbedsforCodeblocksWithLang` while it is being defined). If you remove
```
            \'markdown=pandoc',
```
you'll see it works.

**Comment by bpj** [comment]
Nope. Still same behavior.

**Comment by fmoralesc** [comment]
I can only reproduce it in that case :/

**Comment by bpj** [comment]
I'll get back if I come up with something.

**Comment by bpj** [comment]
It seems this issue is indeed resolved as described above.
