### ISSUE TITLE
Hide pipe and digits denoting headers in gutter

### ISSUE THREAD

**Issue by sheriferson** [vim-pandoc/vim-pandoc-syntax#217]
Is there a way to hide the blue `|` and digits that appear in the gutter and denote the header?

![screen shot 2017-04-12 at 1 55 28 pm](https://cloud.githubusercontent.com/assets/3160968/24979099/deedc01a-1f87-11e7-835f-a66b8b508bb2.png)

I looked at `:help pandoc-syntax-configuration` but didn't find any tips there.

**Comment by sheriferson** [comment]
I shouldn't have been so hasty with opening an issue.
`:set foldcolumn=0` does what I want. Although there is still a subquestion of the best way to change the default things that vim-pandoc(-syntax) turns on, including foldcolumn and spell.

**Comment by fmoralesc** [comment]
The configuration of the plugin is extensive, please consult the help file. 

For the `foldcolumn`, you can use

```
let g:pandoc#folding#fdc = 0
```

and for disabling spell checking,

```
let g:pandoc#spell#enabled = 0
```
