### ISSUE TITLE
Incorrectly highlighting the word after a quote

### ISSUE THREAD

**Issue by elshize** [vim-pandoc/vim-pandoc-syntax#218]
So the problem is when you write a quote that doesn't end with a comma but the next word is the continuation of the sentence. It would be easier to show examples:

> "What?!" **she** exclaimed.

In the above example, *she* would be highlighted even though it is correct.
The highlighting seems to come from an idea that the quote should end with a comma:

> "I agree," he said.

> "Let's do it!" He said that with such confidence.

Both would be correct and neither *he* or *He* would be highlighted.
However, the rule doesn't work when we use either question mark or exclamation point at the end of the quotation and continue the sentence (like the first example).

I tried to figure out where this rule comes from but I failed to do so.
It is a part of syntax though, not spellcheck.

I think this should be fixed but I would also appreciate if anyone could help me with pinpointing what is responsible for that and maybe turning it off.

**Comment by fmoralesc** [comment]
Please put the cursor over the word, and execute:
``` vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
```
That will give a list of the rules which are applied to the text.

However, testing it here, it seems that the problem is that `she` is taken as a grammar error by the spellchecker. If you are using gvim, can you check if `she` is underlined with a blue curly line?

**Comment by fmoralesc** [comment]
Yes, that seems to be the problem. Try

``` vim
:hi link SpellCap Error
```

The highlighting should be even more emphasised. You can disable this with `hi link SpellCap Normal`, although that might have some corner cases.

**Comment by elshize** [comment]
Alright, thanks a lot! I disabled it the way you mentioned. Thanks a lot for the help!

**Comment by fmoralesc** [comment]
@elshize this sort of depends on the way vim recognizes sentences, which is kind of configurable, so there could be some other way to fix this without masking the errors in capitalization (grammar check might have been a bit of an exaggeration :p)

**Comment by elshize** [comment]
Alright, thanks a lot, I'll leave it disabled for now, and maybe will try to dig into it someday :)
