### ISSUE TITLE
Slow when inputting characters

### ISSUE THREAD

**Issue by klassegeljakt** [vim-pandoc/vim-pandoc-syntax#223]
My WPM typing speed is around 50-70, and the characters are displayed at a rate slower than this. I'm running with default configuration on MacVim. Is there any option I should enable/disable, and are  there any other plugins I should look out for?

**Comment by fmoralesc** [comment]
It really depends on the document. It could be the syntax file having pathological input (tables can slow down things, for example). Some things in the folding and autoformatting modules can slow things down as well.

**Comment by klassegeljakt** [comment]
I ran some tests and it turns out another plugin (ntpeters/vim-better-whitespace) was causing the lag.
