### ISSUE TITLE
No syntax file found for 'dart'

### ISSUE THREAD

**Issue by sgon00** [vim-pandoc/vim-pandoc-syntax#232]
```vim
let g:pandoc#syntax#codeblocks#embeds#langs = ["dart"]
```
This will cause the error message: `No syntax file found for 'dart'`
I found out `dart` is not supported. How can I workaround this? Is that possible to add dart support? thanks.

**Comment by fmoralesc** [comment]
Do you have support files for the dart language installed? We simply use whatever vim has.

Check https://github.com/dart-lang/dart-vim-plugin

**Comment by sgon00** [comment]
@fmoralesc thanks a lot. I don't know vim-pandoc-syntax uses whatever vim has. I didn't have dart support installed in vim because I use another editor, vscode (visual-studio-code) when programming dart. After installing dart vim support, vim-pandoc-syntax works. Thank you very much for your help.
