### ISSUE TITLE
no spell check in parens

### ISSUE THREAD

**Issue by Alok** [vim-pandoc/vim-pandoc-syntax#233]
Spell check seems to be disabled when in parens, which is odd for prose.

**Comment by fmoralesc** [comment]
Can you give some sample text where this occurs? I cannot reproduce it.

**Comment by Alok** [comment]
I get it with this: `(testa)`.


-- Alok

**Comment by Alok** [comment]
Nesting in bold or italics fixes it: `*(testa)*`


-- Alok

**Comment by fmoralesc** [comment]
I get 
![screenshot from 2017-11-22 00-24-00](https://user-images.githubusercontent.com/221465/33102090-78157bd2-cf1b-11e7-8c45-607aa0d2fea1.png)
so it seems to work here in both cases.

**Comment by Alok** [comment]
@junegunn 's Rainbow parens is causing the issue somehow.
