### ISSUE TITLE
Question: How to change syntax colors 

### ISSUE THREAD

**Issue by Hipomenes** [vim-pandoc/vim-pandoc-syntax#235]
I'm new to Vim and I just installed all vim-pandoc plugins, which are wonderful. Chapeau! However, there's something I yet haven't manage to do. I've been using Solarized for a while in other contexts, and I've developed a  color-coded note-taking scheme based on it. I was wondering what would be the most efficient way to choose different Solarized colors for basic Pandoc-flavored Markdown (titles, block-quotes, emphasis, etc.) 

Thanks!

David

**Comment by fmoralesc** [comment]
If you know the Solarized highlighting groups, you can link the ones pandoc-syntax uses to those, like this:

``` vim
hi! link pandocHeaderAtx Directory 
```

(`Directory` is just to give an example, I don't know what would be appropriate for Solarized). If you find a good fit, you can create an `after/syntax/` directory in your runtimepath (usually `~/.vim/` for vim, `.coinfig/nvim/` for neovim), and save your config in a file called `pandoc.vim`. That should then be loaded automatically after the main syntax file is, so it will override what the plugin's syntax file has.

**Comment by Hipomenes** [comment]
Thanks so much, fmoralesc! Works like a charm! With one caveat: by establishing links it seems I can only modify color attribution in a specific term (i.e. cterm). When I open a file in GUI (MacVim) highlights changes a bit (specially bold and italics). Any advice? 

D

**Comment by alerque** [comment]
@Hipomenes Color schemes often have different color sets for different terminal types (or they may neglect to implement colors for some terminal types entirely). Graphical vs. terminal colors work a bit differently.

In any event this is an issue you should bring up with the color scheme authors, this plugin does not set any colors, only assigns various syntax patterns to various definitions. Color schemes define what the actual colors (and other font treatments) are.
