### ISSUE TITLE
How to remove fold column

### ISSUE THREAD

**Issue by abers** [vim-pandoc/vim-pandoc-syntax#237]
I am unsure whether this is part of vim-pandoc or vim-pandoc-syntax. Whenever I open a pandoc file a distracting bright white fold column is added to the left of the screen which displays a number on every line based on the heading level. For example, within a section with a ## heading every line has the number 2. How can this be disabled?

**Comment by fmoralesc** [comment]
``` vim
let g:pandoc#folding#fdc = 0
```

See `:help vim-pandoc-folding-module`.

You could also try making the fold column less intrusive by adjusting the FoldColumn highlighting

``` vim
hi! link FoldColumn Normal
```

**Comment by alerque** [comment]
I hope that answered your question @abers. I think the `vim-pandoc` plugin is where this would be more relevant if your issue still isn't resolved. It looks like it might be taken care of, but if not feel free to raise an issue there.
