### ISSUE TITLE
fold method switches to syntax from ruby.vim

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc-syntax#241]
After `:doautocmd Syntax` in a markdown file, `foldmethod` switches from `expr` to `syntax` from `ftplugin/ruby.vim`.

**Comment by Konfekt** [comment]
See https://github.com/tpope/vim-markdown/issues/154 for further details.

**Comment by Konfekt** [comment]
Closed by https://github.com/tpope/vim-markdown/commit/719b046bbec79879add51b7e95415db06a394f30

**Comment by alerque** [comment]
So...is this not a problem for vim-pandoc at all?

**Comment by Konfekt** [comment]
No longer. It used to be, since `markdown.vim` was loaded, too.

**Comment by Konfekt** [comment]
I was wrong. The same issue is reproduced here. https://github.com/vim-pandoc/vim-pandoc-syntax/pull/314 should fix it by the same cure.

**Comment by alerque** [comment]
Closed by #314.
