### ISSUE TITLE
Sorry, no help for pandoc-syntax-configuration and How to set user chars? 

### ISSUE THREAD

**Issue by sgon00** [vim-pandoc/vim-pandoc-syntax#245]
OS: MacOS

I have pathogen installed and have the following in `.vimrc`:

```
execute pathogen#infect()
```

I put `vim-pandoc` and `vim-pandoc-syntax` in `~/.vim/bundle/` and the pandoc plugins are just loaded automatically. 

But, I failed to execute any pandoc helps such as `:help pandoc-syntax-configuration`. Are there any online docs or wiki? 

I plan to set user chars and found somebody mentioned this in issues such as

```
let g:pandoc_syntax_user_chars = {
  \ 'atx': 'H',
  \ 'li': '+' }
```

I put it in `.vimrc` and it doesn't do anything. Since I can not read and find any docs, I am not sure what the correct syntax is. 

Thanks a lot.

**Comment by fmoralesc** [comment]
The documentation is in the plugin folder, in `doc/pandoc-syntax.txt`. The help section itself is installed so it can be invoked with `:help vim-pandoc-syntax-configuration`. I think you want to change `g:pandoc#syntax#conceal#cchar_overrides`, there is no such thing as `g:pandoc_syntax_user_chars`.

**Comment by sgon00** [comment]
@fmoralesc thank you very much for your help. I am able to override cchar now. I just don't really understand why I can't access the doc with `:help` command. I tried in both MacOS and Linux. Both don't work. Maybe because I am using pathogen plugin manager?

**Comment by sgon00** [comment]
I will just close this issue since I know where to find the doc file even if I still can not use `:help` command and don't know why.

**Comment by fmoralesc** [comment]
@sgon00 I think you can fix that issue if you issue the command `:helptags ALL`. See `:help :helptags`.
