### ISSUE TITLE
What font to use for subscript and superscript concealed letters?

### ISSUE THREAD

**Issue by thalesmello** [vim-pandoc/vim-pandoc-syntax#256]
I've just installed the plugin and I'm impressed by it.

Concealed subscript and superscript numbers work just fine, but the letters are missing in my terminal. How could I enable them? I'm surrently using "Sauce Sans Pro Nerd Font".

![image](https://user-images.githubusercontent.com/1127394/51257823-9f96f900-198f-11e9-81e4-d237b9dcdaa0.png)

Also using iTerm2 on MacOS X

**Comment by fmoralesc** [comment]
I'm personally using "Inconsolata", but I know many other fonts should have them (Droid Sans Mono, Ubuntu Mono and Source Code all have them. 

If the problem is with the terminal, I sadly have no suggestions (I'm a Linux user only, so I don't have a way to test).

**Comment by thalesmello** [comment]
It's probably an issue with my terminal then. I'll take a look later.

Meanwhile, I'm trying to disable concealing of superscript and subscript, but the following doens't work:

```
let g:pandoc#syntax#conceal#blacklist = ["subscript", "superscript"]
```

Disabling concealing does work, but I just want to disable the subscript and superscript parts.

```
" Works, but not what I want
let g:pandoc#syntax#conceal#use = 0
```

Do you know what that might be @fmoralesc ?

**Comment by fmoralesc** [comment]
The subscript and superscript definitions are inherited from the latex syntax file, I'm not entirely sure how things can be configured for that. I think g:tex_conceal handles that, I recommend you to take a look at the help on that (`:help g:tex_conceal`).

**Comment by thalesmello** [comment]
Thanks @fmoralesc !

Setting `let g:tex_conceal = "admg"` solves my problem. Thanks.
