### ISSUE TITLE
Need help changing colors in the syntax created by pandoc syntax

### ISSUE THREAD

**Issue by NatalieGates** [vim-pandoc/vim-pandoc-syntax#258]
Please review the following screenshot. Everything looks great accept for the gutter, headings, and lists. As you can see, these items are all a solid light grey color which I find distracting. How can I resolve this? I would like the paragraph symbol to match the header color. I would like the bullets to be white or blue. I would like the gutter area to match the rest of the background.

![Screen Shot 2019-04-02 at 8 46 23 AM](https://user-images.githubusercontent.com/47909481/55404567-2c306c80-5526-11e9-8ad4-93f98478f836.png)

Thanks for your help.

**Comment by fmoralesc** [comment]
Your colorscheme is incomplete, so it is using the defaults for the gutter and conceals.

In your .vimrc you have to add something like

```
au Colorscheme * hi! link Conceal Number
au Colorscheme * hi! link LineNr Normal
au Colorscheme * hi link FoldColumn Normal
```

You can tweak it by changing the final syntax group name (for example, changing `Number` with `Directory`.). See the output of `:hi` to see what groups are available. You can also create new ones, but that is a more complex topic and you should probably look for documentation on that elsewhere.
