### ISSUE TITLE
Plugin code breaks vim's syntax highlighting

### ISSUE THREAD

**Issue by alerque** [vim-pandoc/vim-pandoc-syntax#265]
The change implemented in #191 has managed to break the syntax highlighting for vimscript (at least in my version of Neovim. We should...

1. re-evaluate if this is really the correct code,
2. look into adding some sort of work around for our own file
3. consider contributing a fix to the vimscript syntax upstream (vim? neovim?)

**Comment by fmoralesc** [comment]
I found a fix. I think the issue is that the matched character is the same as the bounding character of the pattern (`/`). A simple fix is to use a different character to delimit the pattern.
