### ISSUE TITLE
conceal?

### ISSUE THREAD

**Issue by laoshaw** [vim-pandoc/vim-pandoc-syntax#282]
can I disable conceal?

also I try to highlight C inside fenced code block and it's not working.

can't use this easily, though I really like to use pandoc-vim-markdown stuff.

**Comment by alerque** [comment]
```vim
set conceallevel=0

let g:pandoc#syntax#codeblocks#embeds#langs = ['c']
```

**Comment by netzego** [comment]
Actually what you want to set is:
`let g:pandoc#syntax#conceal#use = 0`
in your .vimrc.

**Comment by laoshaw** [comment]
that works for un-conceal Thanks!
