### ISSUE TITLE
Italics at end of line wash over rest of file

### ISSUE THREAD

**Issue by alerque** [vim-pandoc/vim-pandoc-syntax#285]
I don't know yet when this started happening –and it might be something I broke earlier today with merges– but my files have started overflowing with italics. Any time a line ends in italics (which the `*` marker at the end of a line) they are not yielding to the end of the file.

```markdown
*test*

thing
```

Renders as:

![image](https://user-images.githubusercontent.com/173595/57876806-f23dd000-781e-11e9-8386-5effa906b10e.png)

Placing even a space at the end of the line fixes the matching.

**Comment by alerque** [comment]
This is caused by the merge of 376f95f1dda2e2ecec3281b499025d73104457c3 from PR #269.

**Comment by fmoralesc** [comment]
Let's revert that for now, and add a note the solve the issue properly
later (I have some changes locally that are related to this)

**Comment by alerque** [comment]
Done in 14c778e.
