### ISSUE TITLE
Issues with highlighting, readability

### ISSUE THREAD

**Issue by TheScrawl** [vim-pandoc/vim-pandoc-syntax#321]
I'm having some trouble with how syntax is being highlighted. It appears that for some reason, lots of syntax is being highlighted with the same color as its written in, making it unreadable. Preferably, there would be no highlighting at all, and the symbols would be written in a nice color.
My terminal (alacritty) has 16 colors set, and my vimrc is set with `set t_Co=16` to make sure no colors other than these 16 colors are used. 
I'm not sure exactly what is going on thats causing this. I'm not using `vim-pandoc` and am using the workaround given, however I've tried installing `vim-pandoc` and this did not solve my issues. Setting different colorschemes almost works sometimes, but the symbols are still highlighted in a color thats rather unreadable.
If needed I can provide any config files that may be helpful.
![2020-04-08-163625_1920x1080_scrot](https://user-images.githubusercontent.com/18385500/78745081-444b8f00-79b7-11ea-9d4c-3552518cc189.png)

**Comment by alerque** [comment]
This plugin itself does not define the colors to be used ... at all. It just groups things into different keyword groups. It is the responsibility of the color scheme to define what colors these groups should be rendered as.

You need to find a color scheme with 16 color support that covers all the default VIM highlight groups available.
