### ISSUE TITLE
Wrong code-block syntax highlight while editing markdown files.

### ISSUE THREAD

**Issue by Icy-Thought** [vim-pandoc/vim-pandoc-syntax#337]
The code-blocks for my markdown documents are not highlighted based on the desired language's syntax, rather based on a neutral code-block syntax-highlighting..

An example of how Rust-lang highlight is expected to look like:
![Screenshot from 2020-06-08 15-50-10](https://user-images.githubusercontent.com/53710398/84038235-fbf12300-a99f-11ea-9359-45f208eca9fd.png)

VS what is currently being displayed through vim-pandoc-syntax highlighting:
![Screenshot from 2020-06-08 15-50-30](https://user-images.githubusercontent.com/53710398/84038301-10352000-a9a0-11ea-940a-65fa2ed3ad15.png)

**Comment by dotcs** [comment]
@Icy-Thought I had the same issue. What helped was to specify the languages which should be highlighted in the vimrc:
```vim
let g:pandoc#syntax#codeblocks#embeds#langs = ["bash", "python", "yaml", "vim"]
```
Maybe that also helps in your case?

**Comment by alerque** [comment]
What Fabian said is the correct answer. Rust is not in the default list of highlighted languages. I checked and it does work as long as you add it to your list.
