### ISSUE TITLE
Setting `...conceal#use = 0` Doesn't Disable Equation $$ Hiding

### ISSUE THREAD

**Issue by mtoohey31** [vim-pandoc/vim-pandoc-syntax#349]
Hello! I may just be misunderstanding how to disable this feature, but I have the following line in my configuration, `let g:pandoc#syntax#conceal#use = 0`, but pandoc syntax is still hiding the "$$" around my equations. The same behaviour is also present for inline math equations. I also tried setting all listed options in the conceal blacklist options help section, but even with all listed options in the list, it doesn't disable this behaviour.

Let me know if there is actually a way to do this and I'm just doing it incorrect, otherwise, let me know if you could use any more information about the behaviour I'm experiencing.

**Comment by alerque** [comment]
Can you double check that it is actually *this* plugin concealing LaTeX math? There are quite a few other plugins out there that add that particular conceal; if you could just double check by disabling this one and making sure the behavior stops that would be appreciated.

**Comment by mtoohey31** [comment]
Yep, I just double checked again by removing it from my vim-plug section and running `PlugClean` then opening the file with equations, and the $$ were not being hidden. Then I re-added it to vim-plug and `PlugInstall`'ed and as soon as I reopened the file the $$ were gone again, so it's definitely related to this plugin.

If you think it might be some kind of interaction between this plugin and another, my dotfiles are [here](https://github.com/mtoohey31/dotfiles) and they have my full `init.vim`.

**Comment by mtoohey31** [comment]
So I've done some more testing, and actually it turns out that this isn't really `vim-pandoc-syntax`'s fault. It turns out that this is happening because I'm using [Yggdroot/indentLine](https://github.com/Yggdroot/indentLine), which enables conceal, so `vim-pandoc-syntax` is actually behaving correctly and disabling conceal, but `indentLine` is enabling it again. I believe the reason why my earlier testing with removing `vim-pandoc-syntax` earlier seemed to fix the issue is because it disabled the syntax highlighting that suggested that certain math formula elements should be hidden or collapsed, or something like that, I don't completely understand it though.

Anyways, TLDR, not `vim-pandoc-syntax`'s fault, just an unfortuate interaction between plugins!

For anyone else that comes across this and is looking for an alternative indent guide, [nathanaelkane/vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides) is the only one that I've found that doesn't use conceal, though it doesn't look anywhere near as nice with my setup. [thaerkh/vim-indentguides](https://github.com/thaerkh/vim-indentguides) also uses conceal and I haven't come across any others.

**Comment by alerque** [comment]
Thanks for the follow-up. Having used such plugins before I know those kind of hacks are cool but do bring a lot of interaction trouble. I wasn't using this plugin at the time but eventually gave up on them.

**Comment by tinyheero** [comment]
Thanks posting this @mtoohey31. I ran into exactly the same issue and disabling the [Yggdroot/indentLine](https://github.com/Yggdroot/indentLine) fixed the issue. It's a shame because the indentLine plugin is amazing. Did you ever find a way to resolve the undesirable interaction?

**Comment by mtoohey31** [comment]
Nope, afaik there's no quick fix, because indentLine uses conceal to conceal a series of spaces or tabs as a few spaces followed by the specified symbol, so if conceal is disabled then indentLine doesn't work, and if it's enabled then `$$` symbols etc. are concealed.

I suppose if you're willing to put in a lot of work to fix it you could attempt to remove the conceal declarations for the relevant symbols inside this vim-pandoc-syntax plugin, but I haven't looked into it so I don't know how much effort that would require.

**Comment by tinyheero** [comment]
Thanks for that information. That is unfortunate. For anyone else who is running into this problem, you can temporarily disable the Yggdroot/indentLine plugin by running `:IndentLinesToggle` and then turn it back on when you need it. 

Hope that helps as a stop-gap solution.

**Comment by stsievert** [comment]
For any Neovim>=0.5 users: https://github.com/lukas-reineke/indent-blankline.nvim doesn't use conceal (instead, it uses Neovim's virtual text feature)
