### ISSUE TITLE
strange underscore and background colors

### ISSUE THREAD

**Issue by laoshaw** [vim-pandoc/vim-pandoc-syntax#358]
Just switched from vim-markdown and immediately noticed I have the first words under a header highlighted with a light-blue background(e.g. XYZ below):

```
## my header

XYZ is something
```

Also I have various random words are highlighted(red) with a underline below.

At the moment it's unusable.

**Comment by fmoralesc** [comment]
This is probably an issue in your colorscheme. vim-pandoc-syntax/vim-pandoc enables spelling, so words like XYZ will be marked as errors. If your colorscheme is not properly setup (or your terminal lacks some features - assuming you are using the terminal), it might display these elements wrongly. You can confirm by executing `set nospell`. Here is what I see in your example (the pink block is my cursor, that is separate from the syntax file):

![Screenshot from 2021-04-25 11-25-58](https://user-images.githubusercontent.com/221465/115999268-226c7c80-a5b9-11eb-90f6-a6d93c769351.png)

**Comment by laoshaw** [comment]
yes `set nospell` fixed them all, thanks a lot.

on a different note, I use vim-markdown meanwhile I am a heavy pandoc user, I expect vim-pandoc-syntax will bring pandoc-related(e.g. table etc) features for me, is this correct? I don't feel vim-markdown and vim-pandoc-syntax are in conflict so far, which is nice.

**Comment by fmoralesc** [comment]
Yes, vim-pandoc-syntax supports a bunch of pandoc's extensions to markdown.
