### ISSUE TITLE
Code syntax highlighting with `vim-pandoc-syntax`

### ISSUE THREAD

**Issue by paniash** [vim-pandoc/vim-pandoc-syntax#360]
Hi!

Recently I discovered that vim has the functionality for syntax highlighting for language specific code block. This is however, disabled by default and can be enabled by adding the following lines in one's `.vimrc`:

```vim
let g:markdown_fenced_languages = [ 'python', 'vim', 'c' ]
```

This would allow syntax highlighting for the above 3 languages. However, this functionality works with the default syntax for markdown in vim and not with `vim-pandoc-syntax`. Is there a way to enable this feature in this syntax plugin?

**Comment by alerque** [comment]
Yes of course! Set this:

```viml
let g:pandoc#syntax#codeblocks#embeds#langs = [ 'python', 'vim', 'c' ]
```

This and many other settings are documented in the online help:

```viml
:help pandoc-syntax-configuration
```

**Comment by paniash** [comment]
@alerque Thanks a lot! Didn't realize there was documentation for a syntax plugin. ;-)
