### ISSUE TITLE
Error with vimtex and vim-pandoc-syntax

### ISSUE THREAD

**Issue by listout** [vim-pandoc/vim-pandoc-syntax#362]
When trying to open a pandoc flavored markdown file [pandoc.markdown] an Error detected while processing function is shown.

![pandoc_error](https://user-images.githubusercontent.com/66715002/127111543-99b4e6dc-c9c2-482e-ae08-7b2228ca9b54.png)

Minimal vimrc

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'lervag/vimtex'
Plug 'vim-pandoc/vim-pandoc-syntax'
call plug#end()

augroup pandoc_syntax
	au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
augroup END
```

Reproduce the issue

```
vim -u init.vim test.md
```

Even tried with vim-plugs lazy loading feature, same issue.

**Comment by alerque** [comment]
Did you close this because you figured it out? What was the resolution?
