### ISSUE TITLE
Cannot turn off conceal for dashes and hrules

### ISSUE THREAD

**Issue by msprev** [vim-pandoc/vim-pandoc-syntax#42]
Even with `let g:pandoc_use_conceal = 0` in my .vimrc dashes and hrules are rendered with conceal. I am using the latest commit (1b602ada1f3bbe5197a877386ecb82b428237d28)

**Comment by munyari** [comment]
@msprev I have the same issue. I think this is supposed to work with vim-pandoc, at least that's what it was designed for
