### ISSUE TITLE
yaml_metadata_block after title block

### ISSUE THREAD

**Issue by fmoralesc** [vim-pandoc/vim-pandoc-syntax#87]
<a href="https://github.com/anntzer"><img src="https://avatars.githubusercontent.com/u/1322974?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anntzer](https://github.com/anntzer)**
_Wednesday Sep 17, 2014 at 07:21 GMT_
_Originally opened as https://github.com/vim-pandoc/vim-pandoc/issues/80_

---

It seems that vim-pandoc fails to recognize YAML metadata blocks that occur after a title block, e.g.

```
% Title
% Author
% Date

---
key: value
...

The main text.
```

For this file, with today's HEAD the metadata block and main text get highlighted in bold.

**Comment by anntzer** [comment]
This is broken again.

**Comment by fmoralesc** [comment]
Thanks for the heads up. I don't know what happened, but it should be fixed now.
