### ISSUE TITLE
Concealing Links

### ISSUE THREAD

**Issue by fncll** [vim-pandoc/vim-pandoc-syntax#92]
Just saw a discussion on the Vim Users list that made me think of a feature request: an option to conceal the target of links so that this line:

```
Go to [google](http://google.com/) to search
```

Becomes:

```
Go to [google] to search
```

When concealed, but would still be highlighted so easily identifiable.

**Comment by Hipomenes** [comment]
Hi! I just added this line to my .vimrc, with no result. Im trying to use the feature to link to relative filenames with standard markdown syntax. Any clue of what might be wrong? I'm suing Vim 8+ and the most recent vim-pandoc version.

Best

**Comment by Hipomenes** [comment]
Is there a way to disable all conceals **except** urls?
